//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniconApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTS
    {
        public System.Guid ID { get; set; }
        public string PRODUCT { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
